#Celphone Startup and The New Password Entrace 

import time

print("-----"*10)
print("\n\n")
time.sleep(1)
print("                  INFINITY PHONE")
print("\n\n")
time.sleep(1)
print("-----"*10)
print("\n\n")
time.sleep(1)
print("                     STARTUP")
print("\n")
time.sleep(1)
print("                       .")
time.sleep(1)
print("                       ..")
time.sleep(1)
print("                       ...")
print("\n\n")
time.sleep(1)
print("-----"*10)
print("\n\n")
time.sleep(1)
print("               PASSWORD REGISTRATION")
print("\n")
time.sleep(1)
senha_1 = input(              "ENTER THE NEW PASSWORD: ")
senha_2 =0
while(senha_1 != senha_2):
    time.sleep(1)
    senha_2 = input("ENTER THE NEW PASSWORD AGAIN: ")
    if (senha_1 != senha_2):
        time.sleep(2)
        print("THE SECOND ENTRECE WAS DIFERENT OF THE FIRST!\nTRAY AGAIN!")
        time.sleep(1)
time.sleep(1)
print("\n\n")
time.sleep(1)
print("-----"*10)
time.sleep(1)
print("\n\n")
time.sleep(1)
print("     CRIATION OF THE NEW PASSWORD WAS SUCCESS!")
time.sleep(1)
print("\n\n")
time.sleep(1)
print("-----"*10)